---



image: 
  name: geerlingguy/docker-ubuntu1604-ansible:latest
  entrypoint: ["/lib/systemd/systemd"]

variables:
  init: "/lib/systemd/systemd"
  opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
 



AnsibleRoleCheck:
  script:
    - hostname
    - sleep 60
    


  
