---

image:
  name: geerlingguy/docker-ubuntu1604-ansible:latest
  entrypoint: [""]
  
testing:
    tags:
      - docker
      
    entrypoint: ["/lib/systemd/systemd"]
    script:
      - ls -l $CI_PROJECT_DI
      - systemctl status
