---




 



AnsibleRoleCheck:
  variables:
    distro: ubuntu1604
    playbook: test.yml
    container_id: $(date +%s)

  script:

    # Download test shim.
    - wget -O ${PWD}/tests/test.sh https://gist.githubusercontent.com/geerlingguy/73ef1e5ee45d8694570f334be385e181/raw/
    - chmod +x ${PWD}/tests/test.sh

    # Run tests.
    - ${PWD}/tests/test.sh

    # Make sure GitLab is running.
    - >
      docker exec ${container_id} curl --insecure -s --head https://localhost/users/password/new
      | sed -n '1p' | grep -q '200'
      && (echo 'Status code 200 test: pass' && exit 0)
      || (echo 'Status code 200 test: fail' && exit 1)
  
  after_script:
    docker rm -f $container_id


  
